# Registration Page Locators

createAnAccount = "//*[@id='kt_login_signup_form']/div[1]/h1"
loginHere = "link:Login here"
firstName = "name:first_name"
lastName = "name:last_name"
country = "xpath://div[@title='United States: + 1']"
phoneNumber = "xpath://*[@id='kt_login_signup_form']/div[2]/div[3]/div/div/input"
email = "name:email"
city = "name:city"
state = "name:state"
fullAddress = "name:address"
posCode = "name:zip_code"
password = "name:password"
confirmPassword = "name:changepassword"
acceptTerms = "id:kt_login_toc_agree"
submitBtn = "id:kt_sign_up_submit"
cancel = "id:kt_login_signup_form_cancel_button"
termsConditions = "link:terms and conditions"

